import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <header className="w-full border-b border-gray-200 p-4 mb-4">
            <nav className="container mx-auto flex items-center justify-between text-sm">
              <div className="flex items-center gap-4">
                <span className="font-semibold">Sponsorship Tracker</span>
              </div>
              <div className="flex items-center gap-3">
                <Link href="/signup" className="text-blue-600 hover:underline">Sign Up</Link>
                <Link href="/login" className="text-blue-600 hover:underline">Login</Link>
              </div>
            </nav>
          </header>
          <main className="container mx-auto px-4">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
