#!/bin/bash
# Competitive Intelligence
# Kører tirsdag og fredag kl 10:00 UTC (11:00 DK)
# Formål: Find konkurrenter i Mathias' problem space

DATE=$(date +%Y-%m-%d)
DAY=$(date +%A)
OUTPUT_DIR="/root/clawd/competitive-intel"
OUTPUT_FILE="$OUTPUT_DIR/$DATE.md"

mkdir -p "$OUTPUT_DIR"

cat << EOF > "$OUTPUT_FILE"
# Competitive Intelligence Report - $DATE ($DAY)

Generated: $(date)

---

## Competitors Found Today:

EOF

echo "🔍 Searching for competitors..."

# Search queries baseret på AI coding/developer productivity space
# Disse skal tilpasses når vi ved præcist hvad Mathias arbejder på
SEARCH_QUERIES=(
    "AI coding assistant 2026"
    "developer productivity AI tools"
    "LLM code generation platform"
    "AI-powered IDE tools"
)

echo "" >> "$OUTPUT_FILE"
echo "### Search Results:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for query in "${SEARCH_QUERIES[@]}"; do
    echo "Searching for: $query"
    echo "" >> "$OUTPUT_FILE"
    echo "#### Query: \`$query\`" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    # Brug clawdbot web_search - dette skal kaldes fra script
    # For nu, gemmer vi queries og Jue kan udfylde resultater senere
    echo "* Results to be filled by Jue via web_search tool" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

cat << EOF >> "$OUTPUT_FILE"

---

## Analysis:

### Key Competitors:
- [Auto-filled]

### Their Positioning:
- [Auto-filled]

### Pricing Models:
- [Auto-filled]

### Gaps/Oppportunities for Mathias:
- [Auto-filled]

---

Generated by Jue 🧙‍♂️
EOF

echo "✅ Competitive intelligence template created: $OUTPUT_FILE"
echo "💡 Jue will fill this using web_search tool"
