#!/bin/bash
# Daily Insight Generator
# Kører hver morgen kl 08:00 DK tid (07:00 UTC)
# Formål: Giv Mathias en konkret insight han kan bruge til arbejde/projects

echo "💡 Generating Daily Insight..."
DATE=$(date +%Y-%m-%d)
INSIGHT_FILE="/root/clawd/insights/${DATE}.md"

mkdir -p /root/clawd/insights

cat << 'EOF' > "$INSIGHT_FILE"
# Daily Insight - $(date +%Y-%m-%d)

## 🎯 What to Focus On Today

### Trending in AI/Dev:
- [Auto-filled by Jue based on research]

### Project Idea Suggestion:
- [Auto-filled based on trends + Mathias' interests]

### Something New to Learn:
- [Auto-filled based on what's hot]

---

Generated by Jue 🧙‍♂️
EOF

echo "✅ Insight template created. Will be sent to Telegram."
