#!/bin/bash
# Daily Insight - Generer og send til Telegram
# Kører kl 07:00 UTC (08:00 DK)

DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="/root/clawd/insights/${DATE}.md"

# Generer insight hvis filen ikke findes
if [ ! -f "$OUTPUT_FILE" ]; then
    cat << 'EOF' > "$OUTPUT_FILE"
# Daily Insight - $DATE

Generated: $(date +\%Y-%m-%d\ %H:%M UTC)

---

## 🔍 What's Happening Today

[Auto-filled by Jue via memory analysis]

## 💡 Task Suggestions

[Auto-filled by Jue analyzing recent work]

## 🎯 Focus Areas

[Auto-filled based on current projects]

---

Generated by Jue 🧙‍♂️
EOF
fi

# Hvis filen findes med indhold, send den
if [ -f "$OUTPUT_FILE" ] && [ -s "$OUTPUT_FILE" ] && [ $(wc -l < "$OUTPUT_FILE") -gt 5 ]; then
    CONTENT=$(cat "$OUTPUT_FILE")
    
    # Gem til variable for Jue at hente
    echo "DAILY_INSIGHT_READY=1" >> /tmp/jueflow-state
    echo "INSIGHT_PATH=$OUTPUT_FILE" >> /tmp/jueflow-state
    echo "INSIGHT_DATE=$DATE" >> /tmp/jueflow-state
    
    echo "✅ Daily insight klar til sending via Jue"
    echo "📝 Path: $OUTPUT_FILE"
    echo "🗓️ Date: $DATE"
else
    echo "⚠️ Ingen insight fil fundet eller filen er tom: $DATE"
fi
