#!/bin/bash
# Proactive Task Suggestions
# Kører hver dag kl 09:00 DK tid (08:00 UTC)
# Formål: Giv Mathias konkrete forslag til hvad han kan arbejde på baseret på context

echo "🎯 Analyzing recent work and suggesting tasks..."

DATE=$(date +%Y-%m-%d)
SUGGESTIONS_FILE="/root/clawd/suggestions/${DATE}.md"

mkdir -p /root/clawd/suggestions

# Læs recent memory
TODAYS_MEMORY="/root/clawd/memory/$(date +%Y-%m-%d).md"
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d)
YESTERDAYS_MEMORY="/root/clawd/memory/${YESTERDAY}.md"

cat << EOF > "$SUGGESTIONS_FILE"
# Task Suggestions - $DATE

## 🎯 Based on Recent Conversations:

### High Priority (from yesterday/today):
$(if [ -f "$TODAYS_MEMORY" ]; then
    grep -E "TODO|IMPORTANT|SKAL|prioritet|vigtig" "$TODAYS_MEMORY" | head -5 || echo "No explicit todos found."
else
    echo "No memory file for today yet."
fi)

### Projects in Progress:
$(if [ -f "$YESTERDAYS_MEMORY" ]; then
    grep -E "projekt|build|udvikl|koder" "$YESTERDAYS_MEMORY" | head -3 || echo "No active projects found."
else
    echo "No memory file for yesterday."
fi)

## 💡 New Ideas Based on Trends:
- [Auto-filled from AI research]

## 🧠 What We Should Learn:
- [Auto-filled based on trending topics]

## 🔥 Quick Wins (under 30 min):
- Review recent memory and update MEMORY.md
- Clean up workspace
- Check for new skills/tools to install

---

Generated by Jue 🧙‍♂️
EOF

echo "✅ Task suggestions generated. Will send to Telegram."
