#!/bin/bash
# Trend-Based Idea Generator
# Kører lørdag kl 09:00 UTC (10:00 DK)
# Formål: Generer produktidéer baseret på trends og pains

DATE=$(date +%Y-%m-%d)
OUTPUT_DIR="/root/clawd/trend-ideas"
OUTPUT_FILE="$OUTPUT_DIR/$DATE.md"

mkdir -p "$OUTPUT_DIR"

cat << EOF > "$OUTPUT_FILE"
# Trend-Based Ideas - $DATE

Generated: $(date)

---

## Top AI/Dev Trends Today:

EOF

echo "🔍 Searching for current trends..."

# Search queries for trends
TRENDS=(
    "AI coding tools 2026 trending"
    "developer productivity AI"
    "LLM applications developers"
    "AI IDE features"
    "what developers hate about AI coding"
)

echo "" >> "$OUTPUT_FILE"
echo "### Trend Searches:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for trend in "${TRENDS[@]}"; do
    echo "📊 Searching: $趋势"
    echo "" >> "$OUTPUT_FILE"
    echo "#### Trend: \`$trend\`" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "* Results to be filled by Jue via web_search" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

cat << EOF >> "$OUTPUT_FILE"

---

## Trending Pains Found:

Based on trends, here are the problems developers are struggling with:

### Pain #1: [Auto-filled]
- **What developers say:** [Auto-filled]
- **Frequency:** [Auto-filled]
- **Monetization potential:** [Auto-filled]

### Pain #2: [Auto-filled]
- **What developers say:** [Auto-filled]
- **Frequency:** [Auto-filled]
- **Monetization potential:** [Auto-filled]

### Pain #3: [Auto-filled]
- **What developers say:** [Auto-filled]
- **Frequency:** [Auto-filled]
- **Monetization potential:** [Auto-filled]

---

## Product Ideas Based on Trends:

### Idea #1: [Name]
**Problem it solves:** [Auto-filled]
**Why now:** [Auto-filled]
**Competitive landscape:** [Auto-filled]
**Monetization:** [Auto-filled]
**Build complexity:** [Auto-filled] (1-10)
**Skill match for Mathias:** [Auto-filled] (%)

---

### Idea #2: [Name]
**Problem it solves:** [Auto-filled]
**Why now:** [Auto-filled]
**Competitive landscape:** [Auto-filled]
**Monetization:** [Auto-filled]
**Build complexity:** [Auto-filled] (1-10)
**Skill match for Mathias:** [Auto-filled] (%)

---

### Idea #3: [Name]
**Problem it solves:** [Auto-filled]
**Why now:** [Auto-filled]
**Competitive landscape:** [Auto-filled]
**Monetization:** [Auto-filled]
**Build complexity:** [Auto-filled] (1-10)
**Skill match for Mathias:** [Auto-filled] (%)

---

## Prioritized Ideas:

| Rank | Idea | Priority Score | Why |
|------|------|----------------|-----|
| 1 | [Auto-filled] | [Auto-filled] | [Auto-filled] |
| 2 | [Auto-filled] | [Auto-filled] | [Auto-filled] |
| 3 | [Auto-filled] | [Auto-filled] | [Auto-filled] |

---

Generated by Jue 🧙‍♂️
EOF

echo "✅ Trend-based ideas template created: $OUTPUT_FILE"
echo "💡 Jue will fill this using web_search tool"
echo "🎯 Ideas prioritized by monetization + skill match"
