#!/bin/bash
# What Did I Learn This Week?
# Kører søndag kl 20:00 UTC (21:00 DK)
# Formål: Review ugens memory og summer lærdomme

DATE=$(date +%Y-%m-%d)
WEEK_START=$(date -d "7 days ago" +%Y-%m-%d)
OUTPUT_DIR="/root/clawd/weekly-learnings"
OUTPUT_FILE="$OUTPUT_DIR/$DATE.md"

mkdir -p "$OUTPUT_DIR"

cat << EOF > "$OUTPUT_FILE"
# Weekly Learning Report - $DATE

Generated: $(date)
Week of: $WEEK_START to $DATE

---

## Key Learnings This Week:

EOF

echo "🧠 Reviewing memory from the last 7 days..."

# Find alle memory filer fra de sidste 7 dage
MEMORY_FILES=$(find /root/clawd/memory -name "2026-*.md" -mtime -7 | sort)

echo "" >> "$OUTPUT_FILE"

if [ -z "$MEMORY_FILES" ]; then
    echo "No memory files found from the last 7 days." >> "$OUTPUT_FILE"
else
    echo "### Memory Files Reviewed:" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    for file in $MEMORY_FILES; do
        filename=$(basename "$file")
        echo "- $filename" >> "$OUTPUT_FILE"
    done
    echo "" >> "$OUTPUT_FILE"
fi

cat << EOF >> "$OUTPUT_FILE"

## What We Learned:

### New Knowledge:
- [Auto-filled by Jue analyzing memory files]

### Mistakes Made & Lessons:
- [Auto-filled - patterns from memory]

### Patterns Identified:
- [Auto-filled - what Mathias likes/dislikes]

### Decisions Made:
- [Auto-filled - why we chose certain directions]

---

## Action Items Going Forward:

### To Keep Doing:
- [Auto-filled]

### To Stop Doing:
- [Auto-filled]

### To Try Next Week:
- [Auto-filled]

---

## MEMORY.md Updates Needed:

Based on this week's learnings, here's what should be updated in long-term memory:

[Auto-filled by Jue]

---

Generated by Jue 🧙‍♂️
EOF

echo "✅ Weekly learning report created: $OUTPUT_FILE"
echo "💡 Jue will analyze memory files and fill this report"
echo "📝 Reviewing $MEMORY_FILES"
